### ISSUE TITLE
Validate that parser is fault tolerant

### ISSUE THREAD

**Issue by gvillafanetapia** [MuttData/pharmacy#9]
From Ben's feedback;

>  It appears the parser isn't fault tolerant.  It threw an exception pretty quickly and ended up stopping production.  I add a catch and a retry to the fetch method.  This cleared the exception we were getting when AWS didn't properly respond, but it may still leave the system open to returning bad data.  Ideally the parser would return an empty array if it had any failures along the way.  Could you add some additional tests to make sure if AWS fails to return data, we don't actually break the application.

So;

1. Analyze what are the point of failures (mainly it seems to be AWS endpoint)
2. Catch necessary exceptions and act accordingly (retry? return null? etc)
3. Maybe the parser should have a try catch block so when there is an error it just returns null and logs the appropiate exception

**Comment by JDSanto** [comment]
Some of the errors found while parsing `sig_initial` (like for example an empty sig is provided) are already fixed in the branch.

Since Ben already added the corresponding code to retry the request up to three times, I think the parser should return in the event of an exception instead of retrying.

I added the commit https://github.com/MuttData/pharmacy/pull/8/commits/be98eedc865c91e8c379572b3011cc4e1e0aa70a which adds a general try/catch clause, and returns the constant `SIG_PARSER_ERROR_RETURN` which at the moment is equal to `null`

**Comment by gvillafanetapia** [comment]
OK, saw that. Sounds good to me

**Comment by gvillafanetapia** [comment]
Define two custom exceptions:

1. `SigParserAWSComprehendException` 
   1. throw when AWS SDK fails
2. `SigParserMalformedInputException` 
   1. throw when input is invalid
2. `SigParserUnexpectedException` 
   1. throw for any other generic exception
